sonar.projectKey=nandhakumar12_Cognitive-adaptive-Ebook
sonar.organization=nandhakumar12
sonar.sources=.
sonar.host.url=https://sonarcloud.io

# Exclude node_modules and tests from analysis
sonar.exclusions=**/node_modules/**, **/*.test.ts, **/*.test.js, frontend/dist/**, backend/dist/**

# Path to coverage reports
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
